name: Check UI Pack Version
on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      pr_number:
        type: number
        required: true

jobs:
  check-ui-pack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.pr_number && format('refs/pull/{0}/head', inputs.pr_number) || '' }}
      
      - name: Check UI pack version
        uses: ./check-version
        with:
          file-path: '.ui-sha'
          pr-number: ${{ inputs.pr_number || github.event.pull_request.number }}
          update-command: 'pnpm run update-ui'
          comment-title: 'UI Version Mismatch'
          comment-body-template: |
            ## UI Version Mismatch 🔄
            
            The UI dependency version in this PR is outdated compared to the main branch.
            
            **Main branch:** `{main_version}`
            **This PR:** `{pr_version}`
            
            To update this PR with the latest version, run:
            ```bash
            {update_command}
            ```
