name: Generate temporalio/ui PR

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      ui_commit_sha:
        description: 'Commit SHA or Branch Name of temporalio/ui. Leave blank for latest SHA'
        required: false
        type: string

      allow_rollback:
        description: 'Allow a commit older than the last merged SHA'
        required: false
        default: false
        type: boolean

      mode:
        description: 'PR mode: test (default) or release'
        required: false
        default: 'test'
        type: choice
        options:
          - test
          - release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UI_REPO: temporalio/ui

jobs:
  build-ui-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Generate UI update PR
        uses: ./generate-pr
        with:
          target-sha: ${{ inputs.ui_commit_sha }}
          allow-rollback: ${{ inputs.allow_rollback }}
          mode: ${{ inputs.mode }}
          file-path: '.ui-sha'
          repository: 'temporalio/ui'
          pack-destination: './packs'
          package-name: '@temporalio/ui'
          pre-pack-commands: 'pnpm svelte-kit sync'
          package-command: 'pnpm package'
          remove-prepare-script: true
          ignore-scripts: true
          pr-title-template: '{mode} temporalio/ui@{short_sha}'
          pr-body-template: |
            This PR uses a local `.tgz` package built from `temporalio/ui@{resolved_sha}`.
            The `.tgz` was created with `pnpm pack` and installed directly into cloud-ui. Use this pr to confirm the commit is functional on the cloud-ui side.

            ### 🧾 Changes in [`temporalio/ui`](https://github.com/temporalio/ui)
            **Commit range:** [`{last_sha}...{resolved_sha}`](https://github.com/temporalio/ui/compare/{last_sha}...{resolved_sha})

            {commit_messages}
          labels: '{mode}-ui'
          draft: 'always-true'
          token: ${{ secrets.GITHUB_TOKEN }}