name: 'Generate Dependency PR'
description: 'Generates a PR with packed dependencies from source repositories (composed from pack and create-pr actions)'
inputs:
  repository:
    description: 'Source repository (owner/name)'
    required: true
  target-sha:
    description: 'Target commit SHA or branch name'
    required: false
    default: ''
  package-name:
    description: 'Name of the package in package.json'
    required: false
  pack-destination:
    description: 'Directory where packed files will be placed'
    required: false
    default: './packs'
  package-command:
    description: 'Build/package command to run before packing'
    required: false
  pack-command:
    description: 'Custom pack command (overrides default pnpm pack)'
    required: false
  file-path:
    description: 'Path to version file (.ui-sha, .registry-sha, etc)'
    required: false
    default: '.ui-sha'
  mode:
    description: 'PR mode (test or release)'
    required: false
    default: 'test'
  pr-title-template:
    description: 'Template for PR title'
    required: false
    default: 'Update {repository} to {short_sha}'
  pr-body-template:
    description: 'Template for PR body'
    required: false
    default: |
      ## Updates {repository} to {short_sha}
      
      Full SHA: {full_sha}
      
      ### Changelog
      {changelog}
  labels:
    description: 'Comma-separated list of labels'
    required: false
    default: ''
  draft:
    description: 'Create as draft PR (true/false/always-true)'
    required: false
    default: 'false'
  token:
    description: 'GitHub token'
    required: true
outputs:
  pull-request-number:
    description: 'The pull request number'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pull-request-url:
    description: 'The pull request URL'
    value: ${{ steps.create-pr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Pack Dependency
      id: pack
      uses: temporalio/pack-dependency-actions/pack-dependency@main
      with:
        repository: ${{ inputs.repository }}
        target-sha: ${{ inputs.target-sha }}
        package-name: ${{ inputs.package-name }}
        pack-destination: ${{ inputs.pack-destination }}
        package-command: ${{ inputs.package-command }}
        pack-command: ${{ inputs.pack-command }}
        file-path: ${{ inputs.file-path }}
        token: ${{ inputs.token }}

    - name: Create PR
      id: create-pr
      uses: temporalio/pack-dependency-actions/create-pr@main
      with:
        repository: ${{ inputs.repository }}
        short-sha: ${{ steps.pack.outputs.short-sha }}
        full-sha: ${{ steps.pack.outputs.full-sha }}
        changelog: ${{ steps.pack.outputs.changelog }}
        mode: ${{ inputs.mode }}
        pr-title-template: ${{ inputs.pr-title-template }}
        pr-body-template: ${{ inputs.pr-body-template }}
        labels: ${{ inputs.labels }}
        draft: ${{ inputs.draft }}
        token: ${{ inputs.token }}