name: 'Create or Update Pull Request'
description: 'Creates a new pull request or updates an existing one. Does not handle git operations - use checkout-pr-branch and commit-and-push actions for that.'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
  branch:
    description: 'The head branch for the PR'
    required: true
  base:
    description: 'The base branch for the PR'
    required: false
    default: 'main'
  title:
    description: 'The PR title'
    required: true
  body:
    description: 'The PR body/description'
    required: true
  labels:
    description: 'Comma-separated list of labels to add'
    required: false
    default: ''
  reviewers:
    description: 'Comma-separated list of reviewers to request'
    required: false
    default: ''
  draft:
    description: 'Whether to create the PR as a draft'
    required: false
    default: 'true'

outputs:
  pr-number:
    description: 'The PR number'
    value: ${{ steps.pr.outputs.pr-number }}
  pr-url:
    description: 'The PR URL'
    value: ${{ steps.pr.outputs.pr-url }}
  pr-created:
    description: 'Whether a new PR was created (true) or existing PR was updated (false)'
    value: ${{ steps.pr.outputs.pr-created }}

runs:
  using: 'composite'
  steps:
    - name: Create or update pull request
      id: pr
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_BASE: ${{ inputs.base }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_LABELS: ${{ inputs.labels }}
        INPUT_REVIEWERS: ${{ inputs.reviewers }}
        INPUT_DRAFT: ${{ inputs.draft }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const branch = process.env.INPUT_BRANCH;
          const base = process.env.INPUT_BASE;
          const prTitle = process.env.INPUT_TITLE;
          const prBody = process.env.INPUT_BODY;
          const labels = process.env.INPUT_LABELS.split(',').filter(Boolean);
          const reviewers = process.env.INPUT_REVIEWERS.split(',').filter(Boolean);
          const draft = process.env.INPUT_DRAFT === 'true';

          // Find existing open PR for this branch
          const { data: prs } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:${branch}`,
            state: 'open'
          });

          if (prs.length > 0) {
            // Update existing PR
            const pr = prs[0];
            console.log(`Updating existing PR #${pr.number}`);

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              title: prTitle,
              body: prBody
            });

            core.setOutput('pr-number', pr.number);
            core.setOutput('pr-url', pr.html_url);
            core.setOutput('pr-created', 'false');
          } else {
            // Create new PR
            console.log('Creating new PR');

            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              body: prBody,
              head: branch,
              base: base,
              draft: draft
            });

            console.log(`Created PR #${pr.number}: ${pr.html_url}`);

            // Add labels if provided
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: labels
              });
            }

            // Request reviewers if provided
            if (reviewers.length > 0) {
              try {
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  reviewers: reviewers
                });
              } catch (e) {
                console.log(`Warning: Could not request reviewers: ${e.message}`);
              }
            }

            core.setOutput('pr-number', pr.number);
            core.setOutput('pr-url', pr.html_url);
            core.setOutput('pr-created', 'true');
          }
