name: 'Update Dependencies'
description: 'Uninstall old packages and install new packed versions'

inputs:
  package-names:
    description: 'Comma-separated list of package names to update (e.g., "@temporalio/ui,@temporal-workers/registry")'
    required: true
  pack-files:
    description: 'Comma-separated list of corresponding pack files to install (e.g., "./packs/ui-abc123.tgz,./packs/registry-def456.tgz")'
    required: true
  package-manager:
    description: 'Package manager to use (npm, pnpm, yarn)'
    required: false
    default: 'pnpm'

runs:
  using: composite
  steps:
    - name: Update dependencies
      shell: bash
      env:
        INPUT_PACKAGE_NAMES: ${{ inputs.package-names }}
        INPUT_PACK_FILES: ${{ inputs.pack-files }}
        INPUT_PKG_MANAGER: ${{ inputs.package-manager }}
      run: |
        PACKAGE_NAMES="$INPUT_PACKAGE_NAMES"
        PACK_FILES="$INPUT_PACK_FILES"
        PKG_MANAGER="$INPUT_PKG_MANAGER"

        # Convert input to arrays (supports both comma-separated and newline-separated)
        # Replace newlines with commas, then split by comma
        PACKAGE_NAMES=$(echo "$PACKAGE_NAMES" | tr '\n' ',')
        PACK_FILES=$(echo "$PACK_FILES" | tr '\n' ',')

        IFS=',' read -ra PACKAGES <<< "$PACKAGE_NAMES"
        IFS=',' read -ra PACKS <<< "$PACK_FILES"

        # Filter out empty elements
        PACKAGES=("${PACKAGES[@]// /}")
        PACKAGES=("${PACKAGES[@]/#/}")
        PACKAGES=($(printf '%s\n' "${PACKAGES[@]}" | grep -v '^$'))

        PACKS=("${PACKS[@]// /}")
        PACKS=("${PACKS[@]/#/}")
        PACKS=($(printf '%s\n' "${PACKS[@]}" | grep -v '^$'))

        # Verify same number of packages and pack files
        if [ ${#PACKAGES[@]} -ne ${#PACKS[@]} ]; then
          echo "Error: Number of packages doesn't match number of pack files"
          echo "Packages: ${#PACKAGES[@]}, Pack files: ${#PACKS[@]}"
          exit 1
        fi

        # Update package.json with file references for all packs
        echo "Updating package.json with file references..."
        for i in "${!PACKAGES[@]}"; do
          package="${PACKAGES[$i]}"
          pack_file="${PACKS[$i]}"

          # Trim whitespace
          package=$(echo "$package" | xargs)
          pack_file=$(echo "$pack_file" | xargs)

          echo "  Updating: $package -> file:$pack_file"

          # Update dependencies
          cat package.json | jq ".dependencies[\"$package\"] = \"file:$pack_file\"" > package.json.tmp
          mv package.json.tmp package.json

          # Add to pnpm overrides to ensure transitive dependencies also use local files
          if [ "$PKG_MANAGER" = "pnpm" ]; then
            cat package.json | jq ".pnpm.overrides[\"$package\"] = \"file:$pack_file\"" > package.json.tmp
            mv package.json.tmp package.json
          fi
        done

        # Run install to resolve all interdependencies
        echo "Running install to resolve all interdependencies..."
        case "$PKG_MANAGER" in
          npm)
            npm install
            ;;
          pnpm)
            pnpm install --no-frozen-lockfile
            ;;
          yarn)
            yarn install
            ;;
          *)
            echo "Error: Unknown package manager: $PKG_MANAGER"
            exit 1
            ;;
        esac

        echo "✅ Dependencies updated successfully"
