name: 'Update Dependencies'
description: 'Uninstall old packages and install new packed versions'

inputs:
  package-names:
    description: 'Comma-separated list of package names to update (e.g., "@temporalio/ui,@temporal-workers/registry")'
    required: true
  pack-files:
    description: 'Comma-separated list of corresponding pack files to install (e.g., "./packs/ui-abc123.tgz,./packs/registry-def456.tgz")'
    required: true
  package-manager:
    description: 'Package manager to use (npm, pnpm, yarn)'
    required: false
    default: 'pnpm'

runs:
  using: composite
  steps:
    - name: Update dependencies
      shell: bash
      env:
        INPUT_PACKAGE_NAMES: ${{ inputs.package-names }}
        INPUT_PACK_FILES: ${{ inputs.pack-files }}
        INPUT_PKG_MANAGER: ${{ inputs.package-manager }}
      run: |
        PACKAGE_NAMES="$INPUT_PACKAGE_NAMES"
        PACK_FILES="$INPUT_PACK_FILES"
        PKG_MANAGER="$INPUT_PKG_MANAGER"

        # Convert comma-separated strings to arrays
        IFS=',' read -ra PACKAGES <<< "$PACKAGE_NAMES"
        IFS=',' read -ra PACKS <<< "$PACK_FILES"

        # Verify same number of packages and pack files
        if [ ${#PACKAGES[@]} -ne ${#PACKS[@]} ]; then
          echo "Error: Number of packages doesn't match number of pack files"
          echo "Packages: ${#PACKAGES[@]}, Pack files: ${#PACKS[@]}"
          exit 1
        fi

        # Remove old dependencies from package.json
        echo "Removing old dependencies from package.json..."
        for package in "${PACKAGES[@]}"; do
          # Trim whitespace
          package=$(echo "$package" | xargs)
          echo "  Removing: $package"

          # Use jq to remove the dependency
          cat package.json | jq "del(.dependencies[\"$package\"])" > package.json.tmp
          mv package.json.tmp package.json

          # Also check devDependencies
          cat package.json | jq "del(.devDependencies[\"$package\"])" > package.json.tmp
          mv package.json.tmp package.json
        done

        # Install new packed versions all at once to resolve interdependencies
        echo "Installing new packed versions..."

        # Build array of pack files
        INSTALL_ARGS=()
        for i in "${!PACKAGES[@]}"; do
          package="${PACKAGES[$i]}"
          pack_file="${PACKS[$i]}"

          # Trim whitespace
          package=$(echo "$package" | xargs)
          pack_file=$(echo "$pack_file" | xargs)

          echo "  Will install: $package from $pack_file"
          INSTALL_ARGS+=("$pack_file")
        done

        # Install all packs in a single command to handle interdependencies
        echo "Running install command with all packs..."
        case "$PKG_MANAGER" in
          npm)
            npm install "${INSTALL_ARGS[@]}"
            ;;
          pnpm)
            pnpm add "${INSTALL_ARGS[@]}"
            ;;
          yarn)
            yarn add "${INSTALL_ARGS[@]}"
            ;;
          *)
            echo "Error: Unknown package manager: $PKG_MANAGER"
            exit 1
            ;;
        esac

        # Final install to ensure all dependencies are resolved
        echo "Running final install to resolve all dependencies..."
        case "$PKG_MANAGER" in
          npm)
            npm install
            ;;
          pnpm)
            pnpm install
            ;;
          yarn)
            yarn install
            ;;
        esac

        echo "✅ Dependencies updated successfully"
