name: Check UI Version

on:
  pull_request:
    branches: [main]
    paths:
      - '.ui-sha'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: temporalio/pack-dependency-actions
          path: .github/actions
          ref: main
      
      - name: Check UI version
        uses: ./.github/actions/check-version
        with:
          file-path: '.ui-sha'
          pr-number: ${{ github.event.pull_request.number }}
          comment-title: 'Sample App - UI Version Check'
          comment-body-template: |
            ## 🔍 Sample App Version Check
            
            The UI dependency version differs between main and this PR.
            
            **Main branch:** `{main_version}`
            **This PR:** `{pr_version}`
            
            To update, run:
            ```bash
            {update_command}
            ```
            
            This check is powered by pack-dependency-actions.
          update-command: 'pnpm run update-ui'