name: Weekly Version Sweep

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: temporalio/pack-dependency-actions
          path: .github/actions
          ref: main
      
      - name: Get open PRs
        id: sweep
        uses: ./.github/actions/version-sweep
        with:
          file-path: '.ui-sha'
          base-branch: 'main'
          labels-filter: ''
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check each PR
        if: steps.sweep.outputs.pr-count > 0
        run: |
          echo "Found ${{ steps.sweep.outputs.pr-count }} open PRs"
          echo "Would check PRs: ${{ steps.sweep.outputs.pr-list }}"
          # In a real scenario, this would trigger check-version for each PR